[package]
name = "jargo"
version = "0.1.0"
authors = ["Nicolas Mohr <Nico.Mohr@gmx.net>"]
edition = "2018"


[dependencies]
clap = "2.32.0"
toml = "0.4.8"
serde_derive = "1.0.79"
serde = "1.0.79"
regex = "1"